### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by pratik-r** [boyan-soubachov/tastyworks_api#1]
Hi,

Thanks for sharing this package. I'm having a problem installing it. Here's the error I'm getting:

> pip install tastyworks

Collecting tastyworks
  Using cached https://files.pythonhosted.org/packages/ef/1d/49a037be75d170db6e8dc2aa9c56fa4bb619e200eb7ad9b4ab3fc8b30e15/tastyworks-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-uyud8r4p\tastyworks\setup.py", line 11, in <module>
        long_desc = file.read()
      File "C:\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 555: character maps to <undefined>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-lkga88im\tastyworks\

Would appreciate if you could help resolve this issue.

Thanks

**Comment by boyan-soubachov** [comment]
Hi @pratik-r , seems like it may be something on your side. Did you come right?

**Comment by pratik-r** [comment]
Hi, it wasn't exactly on my side. It appears to be a problem with pip reading the encoding. I solved it by changing line 11 of setup.py to 
with open('README.md', encoding = "utf8")

**Comment by boyan-soubachov** [comment]
I see, thank you. Will update accordingly.
