### ISSUE TITLE
bug in Tastyworks API 2.2.0 ??

### ISSUE THREAD

**Issue by edmundgyasi** [boyan-soubachov/tastyworks_api#21]
**Describe the bug**
example.py in latest version of tastywork API 2.2.0 is not working. It hangs after  'get remote account method'.

**To Reproduce**
1.  change option expiry to say 2018, 8, 31
2. Then run 'example.py' in latest version 2.2.0 of tastyworks api

**Comment by boyan-soubachov** [comment]
Thanks for reporting this. I will have a look

**Comment by boyan-soubachov** [comment]
Bug investigated and resolved. New major release coming out as unnecessary fields have been removed from some objects.
