### ISSUE TITLE
Switch to asyncio 3.7 syntax

### ISSUE THREAD

**Issue by jonovate** [boyan-soubachov/tastyworks_api#33]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The whole get_event_loop block has been replaced with 1-line asyncio.run() in Py3.7.   Perhaps migration is needed?
https://realpython.com/async-io-python/#async-ios-roots-in-generators  See "The Event Loop and asyncio.run()"

**Additional context**

**Comment by boyan-soubachov** [comment]
Seems like a simple change. Would really appreciate it if you submit a pull request. Otherwise I'll try and get around to it when I have the chance.

**Comment by boyan-soubachov** [comment]
After some thought, I would like to keep backwards compatibility with Python 3.6. Unfortunately I will not be making this change. Thank you for the suggestion.
