### ISSUE TITLE
Is there a way to specify a time range for get_history?

### ISSUE THREAD

**Issue by a-ilango** [boyan-soubachov/tastyworks_api#45]
First of all, thank you for building this reverse engineered unofficial API for tastyworks! Much appreciated!

I was trying to use `TradingAccount.get_history` and it seems it returns transactions for about a month's worth of history. I was wondering if there's a way to specify a time range when querying the main Tastyworks API?

**Comment by boyan-soubachov** [comment]
I haven't had the time or chance to develop this for a while now so I'm not aware unfortunately :)

There might or might be an endpoint served by tastyworks to do that but I would have to investigate. It's a fair assumption though that if none of their clients support it, then the endpoint won't be there.

**Comment by a-ilango** [comment]
I see. The clients do have a way to specify a time window. What tools do you use to investigate the endpoints?

**Comment by boyan-soubachov** [comment]
Hmm, then there should be an endpoint and it should be possible. There are several ways to do this but you basically have to peek into the traffic between the client (phone, desktop or website) and the server. There are multiple tools out there to do this :)

**Comment by a-ilango** [comment]
Thanks! I'll look into it when I get some time.

**Comment by mattypiper** [comment]
extended history available in this PR (does not have a date range, just extends the range and demonstrates how to adjust the dates)

https://github.com/boyan-soubachov/tastyworks_api/pull/56
