### ISSUE TITLE
Dough URI Does Not Respond

### ISSUE THREAD

**Issue by bandwiches** [boyan-soubachov/tastyworks_api#46]
**Describe the bug**
Pretty sure the URI for the Dough module was deprecated.

**To Reproduce**
1. Make a request to the URI (https://trade.dough.com/api/public_watchlists?include_synthetic=true)
2. See no response from server

**Expected behavior**
A response from the server

**Additional context**
Any HTTP GET function will reproduce the error.  The server is still available and responding, but the URI does not.

**Comment by boyan-soubachov** [comment]
Good point. I haven't had the chance to maintain this repo in a while. If you would like to do a PR, I would be happy to review it :)

**Comment by bandwiches** [comment]
I would love to, but I don't know what the correct URI is.  I was actually looking for that exact call when I found this repo and got really excited!  If you can provide any direction (even a google search) on how to figure that out, I'd be glad to correct and submit a pull!

**Comment by boyan-soubachov** [comment]
One way is to open either of their clients (web, app, desktop) and analyse the traffic going through. Many browsers have such tools.

**Comment by bandwiches** [comment]
Is that the more-or-less the best approach?  I'm actually a network engineer so a lot of that is familiar to me, I just assumed there was a better way to do it 😅 but if that's all it takes, I can definitely look further into it.

**Comment by boyan-soubachov** [comment]
That’s about it. 🙂. If you have a different idea, please share 🙂

**Comment by bandwiches** [comment]
Hey sorry for the delay, but I got a quick update on this.  Turns out, the endpoints are now hosted under the TastyWorks API.  I do have the URI's, but since this package has a separate Dough module, I wasn't quite sure how you wanted me to update the package with this update?

**Comment by boyan-soubachov** [comment]
I’m happy for you to move those endpoints and their objects out of the dough package and into the main tastyworks one 🙂

**Comment by bandwiches** [comment]
haha! I'll see what I can do!

**Comment by bandwiches** [comment]
I hope I'm not making this more trouble than it's worth.  I haven't actually used this package but I have referenced it for a personal project.  I'm not exactly adept enough to run the test modules but hopefully this is a good start!  [Pull Request](https://github.com/boyan-soubachov/tastyworks_api/pull/47)

**Comment by boyan-soubachov** [comment]
That's not a problem. I left a comment on the PR, I think we should move the discussion there
